server:
  port: 8080
spring:
  sql:
    init:
      platform: postgresql
      mode: always

  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:postgresql://localhost:5432
    username: salt
    password: secret


  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
